[mysql]
host = "127.0.0.1:3306"
dsn = "sunshine:sharpmysql@(%s)/sharp?timeout=1000ms&readTimeout=1000ms&writeTimeout=1000ms&charset=utf8&parseTime=true&loc=Local"

conn_max_lifetime = 60
max_idel_conns = 20
max_open_conns = 20